export const CATEGORIES = ["All", "Technology", "Marketing", "Design", "Career"];

export const POSTS = [
  {
    slug: "high-impact-tech-portfolio",
    title: "How to Build a High-Impact Tech Portfolio",
    excerpt: "Learn what recruiters actually look for in modern frontend & full-stack roles — and how to showcase real work that gets you hired.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM (1).jpeg",
    category: "Technology",
    date: "Aug 28",
    readTime: "6 min read",
    featured: true,
    content: [
      { type: "paragraph", text: "A strong portfolio is the difference between getting lost in a pile of applications and standing out to the recruiter who scans your work for thirty seconds. In tech hiring, your portfolio is a living proof of exactly what you can ship — not what you claim you can do." },
      { type: "heading", text: "What recruiters actually look for" },
      { type: "paragraph", text: "Forget the idea that a portfolio is a wall of project screenshots. Modern recruiters and hiring managers scan for three things: real, working projects; clear technical depth; and evidence of product thinking. Every project you include should answer: what problem did you solve, how did you build it, and what was the measurable outcome?" },
      { type: "heading", text: "Quality over quantity" },
      { type: "paragraph", text: "Three well-crafted, deeply documented projects beat twelve shallow ones. Recruiters read portfolios under time pressure. Each project needs a one-line summary, the stack you used, a live link or demo, and a short write-up of the hardest engineering decision you made and why." },
      { type: "heading", text: "Show real work, not tutorial clones" },
      { type: "paragraph", text: "Tutorial projects teach you the basics, but recruiters see them everywhere. Instead, build something you actually care about — a tool that solves a personal problem, an open-source contribution, or a project that fills a real gap. Original work demonstrates ownership, initiative, and the ability to scope and ship." },
      { type: "heading", text: "Make it fast, clean, and mobile-first" },
      { type: "paragraph", text: "Your portfolio is also a technical exhibit. If it loads slowly or breaks on mobile, you've told the recruiter everything they need to know about your attention to detail. Optimize images, keep the design minimal, and make sure the most impressive project is immediately visible." },
      { type: "heading", text: "Keep it updated as you grow" },
      { type: "paragraph", text: "A portfolio is never finished. Every internship, project, and skill you add should be reflected. Schedule a short review each month: cut what's outdated, sharpen the language, and elevate your best work to the top. Consistency is what turns a good portfolio into a career-launching one." },
    ],
  },
  {
    slug: "figma-to-code-designers-bridge",
    title: "Figma to Code: A Designer's Bridge",
    excerpt: "Master the workflow designers and developers use to turn UI mockups into clean, production-ready interfaces.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM.jpeg",
    category: "Design",
    date: "Aug 24",
    readTime: "5 min read",
    content: [
      { type: "paragraph", text: "The gap between a static Figma design and a working interface is where many products stall. Understanding how your designs become code is what separates a designer who hands off files from one who ships products. This workflow helps you bridge that gap with confidence." },
      { type: "heading", text: "Design with code in mind" },
      { type: "paragraph", text: "Before you place a single frame, think in systems. Use consistent spacing scales, a defined color palette, and reusable components. When your Figma file mirrors the component structure developers will build, handoff becomes translation rather than interpretation." },
      { type: "heading", text: "Name your layers and components clearly" },
      { type: "paragraph", text: "A Figma file with layers named 'Frame 12' and 'Rectangle 47' is a nightmare to hand off. Use semantic names that map to the interface: 'nav-bar', 'card-title', 'primary-button'. Clear naming reduces back-and-forth and helps developers understand intent at a glance." },
      { type: "heading", text: "Speak the language of spacing and tokens" },
      { type: "paragraph", text: "Engineers think in CSS properties — padding, margin, border-radius, font-size. If your design uses a consistent token system (like 4px, 8px, 16px spacing steps), developers can implement it faithfully and scale it without guesswork. Share your tokens, don't just show your screens." },
      { type: "heading", text: "Collaborate early, not just at handoff" },
      { type: "paragraph", text: "Bring developers into the design process early. A quick review of constraints — loading states, empty states, error states, responsive behavior — before you finalize will save hours of rework later. Great design systems are built together, not handed off." },
    ],
  },
  {
    slug: "scale-meta-ads-without-burning-budget",
    title: "Scale Meta Ads Without Burning Budget",
    excerpt: "A practical playbook for scaling paid social campaigns with measurable ROAS, from structure to creative testing.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM.jpeg",
    category: "Marketing",
    date: "Aug 24",
    readTime: "7 min read",
    content: [
      { type: "paragraph", text: "Scaling paid social isn't about throwing more money at ads. It's about building a system that lets you increase spend while protecting — or even improving — your return on ad spend (ROAS). This playbook walks through the structure, creative, and data habits that make scaling sustainable." },
      { type: "heading", text: "Start with a clean account structure" },
      { type: "paragraph", text: "A messy ad account is the fastest way to burn budget. Structure campaigns around clear objectives and audiences, keep ad sets tight, and make sure tracking is pixel-perfect before you scale anything. Every dollar should have a measurable purpose." },
      { type: "heading", text: "Test creative before you scale" },
      { type: "paragraph", text: "The biggest lever in Meta ads is creative. Run structured testing — one variable at a time across hooks, visuals, and copy — to find what resonates. Only once a creative proves a healthy ROAS should you increase its budget. Scaling a mediocre creative just multiplies waste." },
      { type: "heading", text: "Scale in measured steps" },
      { type: "paragraph", text: "Avoid doubling budgets overnight. Meta's algorithm needs time to re-optimize. Increase spend in gradual steps, monitor performance for a few days, and let the learning phase settle before making the next move. Patience here protects your return." },
      { type: "heading", text: "Watch the right metrics" },
      { type: "paragraph", text: "Optimize for the outcome that matters — purchases, leads, or qualified sign-ups — not vanity metrics like clicks and impressions. Track frequency, cost per result, and ROAS together. When frequency climbs and ROAS drops, it's time to refresh creative or widen the audience." },
    ],
  },
  {
    slug: "data-analytics-for-your-resume",
    title: "Data Analytics You Can Put on Your Resume",
    excerpt: "Go beyond tutorials — use Python, pandas, and real datasets to answer business questions and build portfolio-worthy analysis.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM (1).jpeg",
    category: "Technology",
    date: "Aug 22",
    readTime: "8 min read",
    content: [
      { type: "paragraph", text: "Anyone can follow a tutorial that loads a CSV and prints a few rows. What employers pay for is the ability to turn raw data into decisions. The path to resume-worthy analytics is choosing a real problem, cleaning real data, and delivering a clear, insight-driven conclusion." },
      { type: "heading", text: "Pick a question, not just a dataset" },
      { type: "paragraph", text: "Start with curiosity. Ask a question you genuinely want answered — which store locations over-perform, what drives customer churn, which factors predict a sale. A clear question gives your analysis direction and makes the outcome genuinely useful rather than a series of charts." },
      { type: "heading", text: "Clean data like a professional" },
      { type: "paragraph", text: "Real-world data is messy: missing values, inconsistent formats, outliers. Showing you can clean, validate, and transform data is half the job. Document your steps — the decisions you made about missing data and outliers are exactly what interviewers want to hear about." },
      { type: "heading", text: "Analyze with purpose" },
      { type: "paragraph", text: "Use pandas and Python to explore, aggregate, and test your hypotheses. The goal isn't complex code — it's a defensible answer. Combine descriptive stats, groupings, and simple visualizations to connect the dots between your data and your conclusion." },
      { type: "heading", text: "Present an insight, not a dump" },
      { type: "paragraph", text: "The final deliverable is the payoff. Structure it like a business memo: the question, the approach, the key findings, and a clear recommendation. When you can present an analysis that ends with 'therefore we should do X', you've demonstrated the skill that gets you hired." },
    ],
  },
  {
    slug: "resume-tips-that-get-interviews",
    title: "Resume Tips That Actually Get Interviews",
    excerpt: "Rewrite your resume with the same lens recruiters use — keywords, impact metrics, and a clear narrative in under 60 seconds.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM.jpeg",
    category: "Career",
    date: "Aug 20",
    readTime: "4 min read",
    content: [
      { type: "paragraph", text: "Recruiters and hiring managers spend, on average, under a minute scanning a resume before deciding whether to move on. Your resume has to win that moment. The secret is to write it the way they read it — fast, keyword-driven, and full of measurable impact." },
      { type: "heading", text: "Put impact numbers front and center" },
      { type: "paragraph", text: "Instead of listing duties, list outcomes. 'Managed social media' becomes 'Grew engagement 40% in three months.' Numbers give hiring managers immediate, concrete proof of what you can do. Quantify wherever you can — results, scale, speed, and scope." },
      { type: "heading", text: "Mirror the job description's keywords" },
      { type: "paragraph", text: "Applicant tracking systems filter resumes for keywords. Read the job description and ensure the skills and terms it emphasizes appear naturally in your resume — in your summary, skills, and experience. This isn't gaming the system; it's speaking the recruiter's language." },
      { type: "heading", text: "Lead with a tight, tailored summary" },
      { type: "paragraph", text: "The top of your resume should be a 2-3 line summary that states exactly who you are, what you bring, and what role you're targeting. Tailor it to each application. A focused opening guides the reader to the rest of your story." },
      { type: "heading", text: "Keep it scannable and clean" },
      { type: "paragraph", text: "A cluttered resume is an instant reject. Use clear section headers, consistent formatting, and bullet points that start with strong action verbs. One page for early-career candidates, two for more experience — and never let design confuse the content." },
    ],
  },
  {
    slug: "content-that-converts-clicks-to-community",
    title: "Content That Converts: From Clicks to Community",
    excerpt: "The repeatable content system behind growing a page from 0 to engaged community, without burning out your team.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM.jpeg",
    category: "Marketing",
    date: "Aug 18",
    readTime: "6 min read",
    content: [
      { type: "paragraph", text: "Growing an engaged audience isn't about posting constantly — it's about a repeatable content system that consistently adds value. The brands that win aren't the loudest; they're the most useful. Here's how to build a content engine that turns followers into a community." },
      { type: "heading", text: "Define your content pillars" },
      { type: "paragraph", text: "Start with three to five content pillars — recurring themes that reflect what your audience cares about. Each piece of content should tie to a pillar and serve a clear purpose: to educate, inspire, or entertain. Pillars keep you consistent and prevent random, burnout-inducing posting." },
      { type: "heading", text: "Value first, promotion second" },
      { type: "paragraph", text: "The trust that builds a community comes from giving value without asking for anything in return. Share practical tips, honest insights, and behind-the-scenes. Promotion is a small part of the mix — the majority of your output should make the audience genuinely better off." },
      { type: "heading", text: "Borrow, repurpose, and batch" },
      { type: "paragraph", text: "Don't create every piece from scratch. Turn one long-form idea into a post, a video, and a carousel. Batch-produce content in focused sessions so you stay consistent without living on the feed. Consistency built through batching beats intensity that fizzles out." },
      { type: "heading", text: "Turn engagement into belonging" },
      { type: "paragraph", text: "Comments aren't metrics to grow — they're relationships to nurture. Reply genuinely, ask questions, and highlight your audience's wins. When people feel seen and part of something, clicks turn into community, and community turns into a loyal audience that shows up." },
    ],
  },
  {
    slug: "ui-vs-ux-beginners-guide",
    title: "What Is UI vs UX? A Beginner's Guide",
    excerpt: "Unpack the difference between UI and UX design, the skills each requires, and how they work together to ship products people love.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM.jpeg",
    category: "Design",
    date: "Aug 16",
    readTime: "5 min read",
    content: [
      { type: "paragraph", text: "If you're starting out in design, the terms UI and UX get thrown around almost interchangeably — but they're two distinct disciplines that must work together. Understanding the difference is the first step to choosing your path and speaking the language of product teams." },
      { type: "heading", text: "UX is the experience" },
      { type: "paragraph", text: "User experience (UX) is about the overall feel of using a product. It covers research, information architecture, user flows, and usability — every decision that shapes how easy and satisfying a product is to use. UX designers ask why and how before they ask what something looks like." },
      { type: "heading", text: "UI is the interface" },
      { type: "paragraph", text: "User interface (UI) design is the visual layer — the screens, buttons, colors, typography, and interactions a user sees and touches. UI designers make sure the interface is not only beautiful but coherent and accessible, translating the experience into a visual language." },
      { type: "heading", text: "How they work together" },
      { type: "paragraph", text: "A great product needs both. UX shapes the journey — getting from point A to point B with minimal friction — while UI makes that journey feel polished and intuitive. You can't have one without the other: an unusable but beautiful app frustrates, and a usable but ugly app undervalues the experience." },
      { type: "heading", text: "Choosing your focus" },
      { type: "paragraph", text: "If you love understanding people, solving problems, and mapping flows, UX might be your path. If you're drawn to visual design, color, typography, and detail, UI could be yours. Many roles blend both — especially at startups — so a foundation in each makes you far more versatile." },
    ],
  },
  {
    slug: "landing-your-first-internship",
    title: "First Impressions: Landing Your First Internship",
    excerpt: "A step-by-step guide to finding, applying for, and acing your very first internship — even with no prior experience.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM (1).jpeg",
    category: "Career",
    date: "Aug 14",
    readTime: "6 min read",
    content: [
      { type: "paragraph", text: "Your first internship is a milestone — it's the door that opens the rest of your career. But getting that first offer feels like a catch-22: you need experience to get experience. The good news is that you can break the cycle with a clear, proactive approach." },
      { type: "heading", text: "Build proof before you apply" },
      { type: "paragraph", text: "Without prior work experience, you need other forms of proof: personal projects, certifications, volunteer work, or coursework you can speak to with confidence. Pick a couple of meaningful projects and finish them well. Completed work demonstrates initiative and follow-through." },
      { type: "heading", text: "Tailor every application" },
      { type: "paragraph", text: "Mass-applying with a generic resume rarely works. For each internship, read the description and tailor your application. Highlight the skills and projects that match, and write a short cover note that connects your experience to their specific need. Relevance wins over volume." },
      { type: "heading", text: "Prep for the interview, not just the questions" },
      { type: "paragraph", text: "Interviews for interns aren't tests of senior skill — they're tests of curiosity, coachability, and fit. Prepare thoughtful questions, be honest about what you don't know, and show enthusiasm for learning. Hiring managers bet on your potential and attitude as much as your current skills." },
      { type: "heading", text: "Make the most of week one" },
      { type: "paragraph", text: "Once you're in, the work starts. Show up early, communicate clearly, ask smart questions, and deliver on small tasks reliably. The interns who get letters of recommendation and return offers are the ones who treat even the smallest assignment as an opportunity to learn and impress." },
    ],
  },
  {
    slug: "email-marketing-that-feels-personal",
    title: "Email Marketing That Feels Personal",
    excerpt: "Segment, personalize and automate your email campaigns to build real relationships with your audience — without the spam folder.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM.jpeg",
    category: "Marketing",
    date: "Aug 12",
    readTime: "5 min read",
    content: [
      { type: "paragraph", text: "Email marketing delivers one of the highest returns of any channel, but only when it feels personal. Bombarding a list with generic blasts is how you land in the spam folder and lose subscribers. The difference comes from segmentation, personalization, and genuine value." },
      { type: "heading", text: "Segment your list" },
      { type: "paragraph", text: "Not every subscriber wants the same thing. Segment your list by interests, behavior, or where people joined. Sending tailored content to a smaller, more relevant group almost always outperforms a single message sent to everyone. Relevance is the foundation of personal email." },
      { type: "heading", text: "Write like a person, not a brand" },
      { type: "paragraph", text: "Avoid stiff corporate language. Write the way you'd write to a friend — warm, clear, and human. Use names, ask questions, and structure emails around a single useful idea. People don't unsubscribe from emails they genuinely look forward to opening." },
      { type: "heading", text: "Automate the journey, not the spam" },
      { type: "paragraph", text: "Automation is powerful when it's triggered by real actions — a welcome sequence after signup, a follow-up after a purchase, a re-engagement nudge for inactive subscribers. Let the recipient's behavior drive what they receive, so every message arrives at the right moment." },
      { type: "heading", text: "Respect the inbox" },
      { type: "paragraph", text: "Deliverability depends on trust. Keep your sending consistent, honor unsubscribe requests immediately, and monitor your open and spam rates. When you treat subscribers' attention as a gift rather than a resource to exploit, they reward you with opens and loyalty." },
    ],
  },
  {
    slug: "seo-basics-get-found-on-google",
    title: "SEO Basics: Get Found on Google",
    excerpt: "Learn the fundamentals of on-page SEO and content structure so your pages actually rank and drive organic visitors.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM (1).jpeg",
    category: "Marketing",
    date: "Aug 10",
    readTime: "6 min read",
    content: [
      { type: "paragraph", text: "Organic search is one of the most valuable traffic sources there is — free, consistent, and highly qualified. But ranking on Google isn't luck. It's the result of doing the fundamentals well: creating content people actually want and structuring it so search engines understand it." },
      { type: "heading", text: "Search for the searcher's intent" },
      { type: "paragraph", text: "Before writing anything, understand what the searcher actually wants. Are they researching, comparing, or ready to act? Match your content to the intent — an informational query deserves a helpful guide, not a sales pitch. Content that satisfies intent gets ranked." },
      { type: "heading", text: "Structure pages for clarity" },
      { type: "paragraph", text: "Use a clear title, a compelling meta description, and heading hierarchy (H1, H2, H3) that reflects your content's structure. Break text into readable sections. Search engines rely on structure to understand your page, and humans rely on it to actually read it." },
      { type: "heading", text: "Build topical depth and internal links" },
      { type: "paragraph", text: "A single thin page rarely ranks. Cover a topic thoroughly, and link between related pages on your site to help search engines map your content and pass authority. A small cluster of interlinked pages on one theme often outperforms one isolated article." },
      { type: "heading", text: "Be patient and measure" },
      { type: "paragraph", text: "SEO is a long game. Rankings take time to build, so publish consistently and track your performance with tools like Google Search Console. Watch what's getting impressions, refine what's underperforming, and keep serving the search intent better than the page above you." },
    ],
  },
  {
    slug: "nextjs-modern-frontend-2026",
    title: "Next.js & Modern Frontend in 2026",
    excerpt: "A practical tour of the modern React stack — Next.js, Tailwind, and server components — for building fast, scalable interfaces.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM.jpeg",
    category: "Technology",
    date: "Aug 9",
    readTime: "7 min read",
    content: [
      { type: "paragraph", text: "Frontend development has changed dramatically — and Next.js sits at the center of modern React. Combining React's component model with server-side rendering, routing, and built-in optimizations, it's the foundation for the fast, scalable interfaces that teams ship today." },
      { type: "heading", text: "Why Next.js leads the stack" },
      { type: "paragraph", text: "Next.js brings together the best of both worlds: static generation for speed, server rendering for SEO, and a file-based routing system that's simple to understand. It ships with image optimization, performance tooling, and a build pipeline that handles the hard parts for you." },
      { type: "heading", text: "Server components change the game" },
      { type: "paragraph", text: "Modern React and Next.js let you decide where each piece of your UI runs — on the server or the client. Server components render on the server, sending only the HTML and data the client needs, which means faster loads, smaller bundles, and cleaner code with less boilerplate." },
      { type: "heading", text: "Style with Tailwind CSS" },
      { type: "paragraph", text: "Tailwind CSS has become the default choice for styling in the React ecosystem. Utility-first classes make UI fast to build, consistent, and easy to maintain — especially when paired with component abstraction. The result is interfaces that look great without hunting through stylesheets." },
      { type: "heading", text: "Build a real project to learn" },
      { type: "paragraph", text: "The fastest path to confidence is building something real. Set up a Next.js app, add Tailwind, create routes, fetch data, and deploy it. Every feature you ship — a page, an API route, an optimized image — turns concepts into muscle memory you can show to employers." },
    ],
  },
  {
    slug: "color-type-spacing-design-fundamentals",
    title: "Color, Type & Spacing: Design Fundamentals",
    excerpt: "The visual building blocks every designer needs — color theory, typography pairing, and spacing systems that make layouts feel polished.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM (1).jpeg",
    category: "Design",
    date: "Aug 6",
    readTime: "5 min read",
    content: [
      { type: "paragraph", text: "Great design often looks effortless, but it's built on a few core fundamentals. Color, typography, and spacing are the three pillars that determine whether an interface feels polished or amateur. Master these and every layout you create will look intentional." },
      { type: "heading", text: "Color with purpose" },
      { type: "paragraph", text: "Color guides attention and communicates mood, but it should never be decorative background noise. Use a small, intentional palette — a primary color for actions, neutrals for structure, and accent colors sparingly. Ensure contrast for readability and use color consistently to reinforce hierarchy." },
      { type: "heading", text: "Typography is the voice" },
      { type: "paragraph", text: "Font choice shapes how your message is received. Pair a strong display type for headlines with a highly readable body type, and keep the pair consistent. Mind the details — line height, letter spacing, and hierarchy — because legible, well-set type makes content trustworthy." },
      { type: "heading", text: "Spacing creates rhythm" },
      { type: "paragraph", text: "Whitespace isn't wasted space — it's what lets your design breathe. Use a consistent spacing scale (multiples of a base unit) so distances feel coherent. Group related elements closer together and separate distinct sections. Good spacing directs the eye and reduces visual clutter." },
      { type: "heading", text: "Combine them into a system" },
      { type: "paragraph", text: "The magic happens when these three work together as a system. Define your palette, your type scale, and your spacing tokens once, then apply them consistently across every screen. Consistency is what turns individual good choices into a cohesive, professional product." },
    ],
  },
  {
    slug: "acing-your-first-internship-playbook",
    title: "Acing the Attitude: First Internship Playbook",
    excerpt: "From writing a standout application to making a strong impression on week one, this playbook sets you up for a great first internship.",
    image: "/blog/WhatsApp Image 2026-09-03 at 10.37.41 AM.jpeg",
    category: "Career",
    date: "Aug 3",
    readTime: "6 min read",
    content: [
      { type: "paragraph", text: "Your attitude and approach in the first few weeks of an internship often matter more than your skill level. Companies hire interns for their potential — your mindset and work ethic are what turn that potential into a standing invitation to join the team." },
      { type: "heading", text: "Own your onboarding" },
      { type: "paragraph", text: "Don't wait to be spoon-fed. Review the docs, explore the codebase or processes, and come prepared with thoughtful questions. Show that you're self-sufficient and genuinely curious from day one. The interns who ask great questions and figure things out get noticed immediately." },
      { type: "heading", text: "Communicate like a professional" },
      { type: "paragraph", text: "Clear, timely communication is a superpower. Update your mentor on progress, flag blockers early, and ask for feedback without being defensive. When you run into problems, bring potential solutions, not just the problem. Professional communication builds trust fast." },
      { type: "heading", text: "Deliver reliably on small tasks" },
      { type: "paragraph", text: "Every small task is a test of reliability. Meet deadlines, pay attention to detail, and finish what you start. A track record of shipping solid small work is the fastest path to being trusted with bigger, more meaningful responsibilities." },
      { type: "heading", text: "Leave a lasting impression" },
      { type: "paragraph", text: "End the internship as you started it — with energy and gratitude. Document what you accomplished, ask for a reference and feedback, and stay in touch with your network. The relationships and reputation you build now become your biggest asset for the next opportunity." },
    ],
  },
];
